branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: backend2
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 18.06.1-ce
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
